### ISSUE TITLE
OBS closes without warning after 30 minutes if stream is considered offline

### ISSUE THREAD

**Issue by d4s1r** [loopy750/SRT-Stats-Monitor#11]
Hi there,

I am using OBS 27.2.4 and I am connecting via JS-Websocket (with 4.x compat).

I did some testing in order to make sure I can leave everything in idle mode. However, after the stream is considered offline for about 30 minutes (estimated), **restarting** the SRT-source causes OBS to close. There is no crash report in the files OBS creates.

I will test this further. What kind of further information do you require in order to troubleshoot this?

Thanks for the awesome tool!

Cheers

**Comment by loopy750** [comment]
Hi. I've never come across this issue, but it could also be I've never started a test after 30 minutes. Is it somehow caused by this program or just an issue with OBS and/or WebSocket, i.e. does OBS still close if this program isn't running? If it's only OBS related, there wouldn't be anything I could do about that.

**Comment by mkordowiak** [comment]
I've had same issue with WebSocket 4. Randomly OBS just crashes, without any message. usually after 20-40 minutes of stream. Just process being terminadet. Often when sceen was switching. Tried to uninstall any additional plugins, but issue was still happening.

After I've switched to WebSocet 5, things starts to work properly. Recently I streamed for over 4 hours without any crash.

**Comment by d4s1r** [comment]
Hi there,
after upgrading to OBS 28,, running Websocket 5.0 and changing to `NodejsFileSystem=2` it did not crash. I will continue testing, but it seems that any of these fixed the issue.
Thanks a lot!
