### ISSUE TITLE
bad CPU type in executable

### ISSUE THREAD

**Issue by chilledsheep** [loopy750/SRT-Stats-Monitor#12]
getting "bad CPU type in executable" error when trying to start on Apple M1

**Comment by loopy750** [comment]
Unfortunately I don't have any Apple hardware to troubleshoot with. Some quick searching shows it could be some incompatibility issue with the hardware. There's something called Rosetta 2 which you can try to install if see if that does anything. I'm looking into it and awaiting a response to further understand if this is the likely cause.
