### ISSUE TITLE
Rtmp mode wont change scene on Connection Lost

### ISSUE THREAD

**Issue by shaddowgigs** [loopy750/SRT-Stats-Monitor#13]
I enabled the rtmp server option using nginx to receive the feed from a gopro and everything seems to be working except when the signal disconnects. Instead of changing to the fallback scene it just stays on Live or low bitrate scene with the last frame of the feed. When the image comes back live it refreshes itself but doesn’t go away when signal lost. The only way to have it react is to go on the properties and exit out, then it goes to the signal lost scene but thats not an option once you are outside. What could be the issue here?

**Comment by loopy750** [comment]
Hi. I have a few things I have to do IRL before I get a proper chance to take a look.

Does changing ```RISTFailMode1=``` and/or ```RISTFailMode2=``` make a difference?

What is the NGINX file? I've tested with mine that is this version: https://github.com/loopy750/NGINX-Stats-Monitor/blob/master/modifications/nginx/nginx.conf

And used this NGINX release: https://github.com/illuspas/nginx-rtmp-win32/releases/tag/v1.2.1

**Comment by DJDevil2K** [comment]
When i use the nginx server on my windows computer, does it work ? Because when i entry my local ip and port in the conf file, loop show stable connection the whole time even when the stream is offline.

**Comment by loopy750** [comment]
Does it look like everything is working at it should at http://127.0.0.1:8080/stat ? That's the page where the stats are grabbed.

**Comment by jedivader20** [comment]
> Hi. I have a few things I have to do IRL before I get a proper chance to take a look.
> 
> Does changing `RISTFailMode1=` and/or `RISTFailMode2=` make a difference?
> 
> What is the NGINX file? I've tested with mine that is this version: https://github.com/loopy750/NGINX-Stats-Monitor/blob/master/modifications/nginx/nginx.conf
> 
> And used this NGINX release: https://github.com/illuspas/nginx-rtmp-win32/releases/tag/v1.2.1

Replying here so as to not duplicate the issue. I'm experiencing the same problem. I've setup two config files, one for SRT and the other for RTMP. SRT works fine, however when using RTMP, I don't get a scene change, it constantly reports stream down, and has a very high (~3000ms) ping for HTTP. The obs-websocket-http configuration is identical between the two configuration files.

![image](https://github.com/loopy750/SRT-Stats-Monitor/assets/5639993/3547a353-2ade-477b-bf56-d1a57174bc68)

Using the following configuration;
![image](https://github.com/loopy750/SRT-Stats-Monitor/assets/5639993/497a0092-ded5-431e-b101-428510ac5e64)

Using the quoted nginx release and conf file, which is receiving/publishing the stream and stats just fine.

**Comment by jedivader20** [comment]
Confirming same behaviour using obs-websocket-js, so this is looking like a OBS Web Socket plugin issue, but it works fine with an SRT input?

**Comment by loopy750** [comment]
RTMPServerPort should be **8080**, not **1935**

Confirm _nginx-rtmp-module_ is running by browsing **http://127.0.0.1:8080/stat**

**Comment by jedivader20** [comment]
> RTMPServerPort should be **8080**, not **1935**
> 
> Confirm _nginx-rtmp-module_ is running by browsing **http://127.0.0.1:8080/stat**

![image](https://github.com/loopy750/SRT-Stats-Monitor/assets/5639993/14ae0085-e03b-4682-b941-4f187cd80561)

Changing from 1935 to 8080 resolved the ping issue but not the scene changing issue.

![image](https://github.com/loopy750/SRT-Stats-Monitor/assets/5639993/5cc3d768-19c8-4075-862a-f281b9037bb1)

Scene is active, Media Source matches the config file and is live.

**Comment by loopy750** [comment]
> Changing from 1935 to 8080 resolved the ping issue but not the scene changing issue.

Not sure what you mean specifically. Check you've followed this part before troubleshooting further: **https://github.com/loopy750/SRT-Stats-Monitor#obs-studio-required**

**Comment by loopy750** [comment]
Disregard previous post.

Settings that work for me during testing are...

My nginx config is taken from here:
**https://raw.githubusercontent.com/loopy750/NGINX-Stats-Monitor/master/modifications/nginx/nginx.conf**

And my testing is via Larix Screencaster using the config:
**rtmp://x.x.x.x/live/stream1**

**Comment by jedivader20** [comment]
Understood, I now recognise where I went wrong. Working as intended.
