### ISSUE TITLE
LBR scene not triggering

### ISSUE THREAD

**Issue by manueldev** [loopy750/SRT-Stats-Monitor#15]
Hello. I'm trying the app for the first time and it's great. Very easy to configure. Now, I had a problem to activate the LBR scene. If I call the scene "Main LBR" it is not activated (even though the message "live LBR" appears in the app window). After a few hours I called the scene in OBS with the name "live LBR" and it works without problems. The scene is activated.

My OS is windows 11. My obs is 29 64bit version and Loopy version is v1.1.0.

I hope this information is useful.

**Comment by loopy750** [comment]
Hello. I'm not sure what you mean by trying to call the scene, or the type of configuration you have setup. LBR scene will only function with `SceneLBREnabled=true` and the bitrate is low.

If the main scene is called `live` then the LBR scene will need to be called `live LBR`.

If you can share your `config.ini` file, removing all passwords of course, it will help me know how it's being used.

**Comment by manueldev** [comment]
Okay. Now I understand. I thought the LBR scene could have any name + LBR at the end. My main scene is called "live". That's why with "live LBR" it works.
