### ISSUE TITLE
SRT Monitor won't change to BRB fail scene

### ISSUE THREAD

**Issue by GORDIE1021** [loopy750/SRT-Stats-Monitor#16]
I  just updated  to OBS Studio 29.  Now, SRT Monitor won't change to BRB fail scene.  I switched to older version of OBS, but same problem.  Reinstalled OBS Studio 29 since older version had same problem.  When SRT Monitor connects, scene switches to the  scene intro/ scene OK as usual, but when source fails, SRT monitor stays there with black screen.

**Comment by loopy750** [comment]
Without knowing your current or previous configuration, it is too hard for me to say what could be causing this. OBS Studio 29 has worked fine for me and others.

So I'd recommend start from the beginning with the quick start guide: https://github.com/loopy750/SRT-Stats-Monitor/blob/main/modifications/resources/quick_start_guide.md

or at the very least, importing this configuration and see if that works successfully: https://raw.githubusercontent.com/loopy750/SRT-Stats-Monitor/main/modifications/resources/Loopy_SRT_Monitor.json
