### ISSUE TITLE
chatbot support to scene switching

### ISSUE THREAD

**Issue by thegamingstig** [loopy750/SRT-Stats-Monitor#17]
Is there something where I can include a chatbot to message chat if my scene had switch to low bitrate/brb?

**Comment by loopy750** [comment]
Thus can be achieved using a program such as AdiIRC is this - a guide here: https://github.com/loopy750/SRT-Stats-Monitor#adiirc

It takes around 5 minutes to setup, and will tell you whenever your stream(s) are offline/online, including switched to low bitrate.

![image](https://user-images.githubusercontent.com/35911135/215765101-ca569fbf-002c-4072-b3f8-d01e309144c4.png)

**Comment by loopy750** [comment]
This can be achieved using a program such as AdiIRC is this - a guide here: https://github.com/loopy750/SRT-Stats-Monitor#adiirc

It takes around 5 minutes to setup, and will tell you whenever your stream(s) are offline/online, including switched to low bitrate.

![image](https://user-images.githubusercontent.com/35911135/215765101-ca569fbf-002c-4072-b3f8-d01e309144c4.png)

**Comment by loopy750** [comment]
Closing this as it's not an issue nor a bug, and the feature is already possible and documented, with no bugs that I'm aware of.
