### ISSUE TITLE
AdiIRC doesn't work well

### ISSUE THREAD

**Issue by commanderphu** [loopy750/SRT-Stats-Monitor#18]
I've installed AdiIRC to controll my Stream Commands. 
I follow the steps on https://github.com/loopy750/SRT-Stats-Monitor/blob/main/modifications/adiirc/guide/README.md

But nothing works

**Comment by loopy750** [comment]
I just added to that guide which should solve the problem, if not already done, else it's hard for me to know what went wrong.

The first step is:

- Edit Loopy SRT Monitor's _config.ini_ file to enable `FileStatusOutput=true`
