### ISSUE TITLE
datarhei Core SRT integration

### ISSUE THREAD

**Issue by svenerbeck** [loopy750/SRT-Stats-Monitor#19]
Hi there!

I am reaching out to say how much I appreciate the fantastic work you and your team have done so far. The SRT-Stats-Monitor tool is already fantastic, but I think it would be even better if [datarhei Restreamer](https://github.com/datarhei/restreamer) and [Core](https://github.com/datarhei/core) were integrated into it.

I'm excited about the possibility of seeing this integration become a reality, and I genuinely believe that it would significantly enhance the tool's functionality.

Here is the URL to the API from datarhei Core. [https://docs.datarhei.com/core/api-ffmpeg/process/state](https://docs.datarhei.com/core/api-ffmpeg/process/state)

Thank you so much for taking the time to consider my suggestion. Keep up the great work!

Cheers,
Sven

**Comment by loopy750** [comment]
That's quite a formal compliment, thank you. I did take a quick look but I'm a little stuck at the moment, maybe you know a little more. I got Restreamer going, setup the configuration via 8080 port, setup an SRT stream via port 6000 and can see that in the preview, but unsure how to get the API to report back the current stream stats.

**Comment by loopy750** [comment]
Beta version available:

https://github.com/loopy750/SRT-Stats-Monitor/tree/beta

**Comment by svenerbeck** [comment]
Hello [loopy](https://github.com/loopy750). That's fantastic! [electronic high5] I'll start testing it hard on Monday or Tuesday. Please note that I'll provide feedback on the beta version next week after testing it. Looking forward to sharing my thoughts with you! One thing I can already say: A shoutout on Datarhei's social media is guaranteed for you!  🚀

Cheerio Sven

**Comment by loopy750** [comment]
Integrated. Reopen if any issues.
