### ISSUE TITLE
How do you get the bitrate of each of the two SRT streams?

### ISSUE THREAD

**Issue by FelipeSanchezCalzada** [loopy750/SRT-Stats-Monitor#20]
Thank you for contributing to open source software, this project is really inspiring.
I'm trying to recreate something similar in Angular, but I have a problem. I thought I could get the bitrate of the SRT stream with obs-webshocket but I can't find the way.

# My question:
### How do you get the bitrate of each of the two SRT streams?

Sorry for opening this as a problem, it really is not.
Thank you very much!

**Comment by loopy750** [comment]
It depends on what is being used to stream. If it's a server such as srt-live-server (modded version) or BELABOX, bitrate stats are easily available. If it's direct to OBS SRT, there is currently no method of fetching bitrate.

**Comment by FelipeSanchezCalzada** [comment]
Okay, that's just what I thought.

Thank you so much!
