### ISSUE TITLE
No video playback after 2nd reconnection

### ISSUE THREAD

**Issue by thegamingstig** [loopy750/SRT-Stats-Monitor#22]
My SRT only reconnects and scene switch after my first lost signal reconnection. When I lost signal for the 2nd time and restart, the mediasource won't display the video and scene won't switch,  even though Larix says there is signal. 

So far I had to stop-and-play on the media source in order to get video feed back up and scene switch.

**Comment by loopy750** [comment]
Can you confirm you've made these changes? https://github.com/loopy750/SRT-Stats-Monitor#obs-studio-required

**Comment by thegamingstig** [comment]
I retype the settings and I finally got video playback from reconnection, but....there is no audio when reconnecting from signal lost

**Comment by thegamingstig** [comment]
Update...made some change to Larix advance setting. Audio is back. I'm good.
