### ISSUE TITLE
[Feature Request] Scenes that get ignored by SRT

### ISSUE THREAD

**Issue by Pillowg1rl** [loopy750/SRT-Stats-Monitor#24]
Simple but easy:
Define Scenes that are getting ignored when it comes to automatic switching.
For Example: I have a scene with the Text "Currently no Audio" but the video-signal and vise versa.
I can control this via Touchportal or OBS Websocket on my phone.
But SRT keeps switching to the other scene... 

Would be awesome to have this feature :)

**Comment by loopy750** [comment]
Unless I'm mistaken, sounds like the feature `SceneBypass`, explained in the readme file:

```
SceneBypass
	Possible values: none, scene name
	The OBS scene that, when manually selected, will pause the program and prevent any automatic scene changes. The default setting of "none" disables this feature. 
	For additional bypass scenes, add SceneBypass2, SceneBypass3 ... SceneBypass8, SceneBypass9 to the config file.
```
