### ISSUE TITLE
How does loopy's work with restreamer?

### ISSUE THREAD

**Issue by amarmashruwala** [loopy750/SRT-Stats-Monitor#26]
Is it restreamer to obs or obs streaming to restreamer ?

**Comment by loopy750** [comment]
I'm really not sure if or how anyone has implemented it. I tested using only OBS to Restreamer, I assumed using OBS as the receiver was also possible. Someone really wanted it as a feature, so I had assumed it could be used that way. They said they would test it and let me know, but I never heard back from them.

**Comment by amarmashruwala** [comment]
Ok so I would like to use it OBS -> Restraamer.

I can make OBS the SRT caller and Restreamer the SRT listener I believe.

Have your loopys SRT stats monitor installed on the OBS PC and hopefully it
will does it magic scene switching as needed.

Thanks

**Comment by amarmashruwala** [comment]
> I'm really not sure if or how anyone has implemented it. I tested using only OBS to Restreamer, I assumed using OBS as the receiver was also possible. Someone really wanted it as a feature, so I had assumed it could be used that way. They said they would test it and let me know, but I never heard back from them.

ok i see. so that makes sense, if using restreamer as the sender and OBS as receiver. maybe i will try the other way around. cheers
