### ISSUE TITLE
can't download the installer

### ISSUE THREAD

**Issue by Yinks87** [loopy750/SRT-Stats-Monitor#28]
You can't download the installer on windows. The installer always get detected as malware and been deleted.

**Comment by loopy750** [comment]
False positive, and possibly because the files aren't digitally signed.

**Comment by Yinks87** [comment]
Maybe... i tried to permit the installer on windows, but it doesn't work. Windows always delted the installer.. i downloaded the portable version and set it up new with the portable one. This works for me.

**Comment by loopy750** [comment]
I've add a .zip file for the installer, that might help the situation for some.

**Comment by Yinks87** [comment]
thx a lot. This is one of the best tools for IRL streaming, thank you so much for your great work!
