### ISSUE TITLE
Prevent Auto Switch when specific scene is selected

### ISSUE THREAD

**Issue by shaddowgigs** [loopy750/SRT-Stats-Monitor#3]
Here's my scenario, I do food deliveries Live and when I get to a client's building/apartment I manually change the scene to a "Droping off, BRB" Scene. The problem is when I get to the elevator for example the signal drops, and it overrides my scene and changes to the low bitrate scene and eventually the signal gets better and back to the live scene showing the client apartment and I don't want to do that. I would like the Scene to stay on my custom scene until i manually change it back to live and from there on it can change by itself.

**Comment by soviet-warrior** [comment]
I was going to request this feature myself.  Thanks for adding it!  I am planning to use a drone in some of my streams and I wanted to be able to switch to the drone video scene and prevent the application from switching back to my normal scenes while I'm flying the drone.
