### ISSUE TITLE
[Feature Request] Webhooks

### ISSUE THREAD

**Issue by modemmike** [loopy750/SRT-Stats-Monitor#30]
I was just wondering if there is some way to fire a webhook on stream loss? I often run my gear without any screens on so it takes me a while to notice that I'm no longer live. A webhook could be called to send a text (or whatever).

Thanks!

**Comment by loopy750** [comment]
I'm not entirely sure if what you're after is beyond the scope of what I might be able to do, however something that should suffice, is making use of AdiIRC, a program in which I've gone into some detail.

Firstly, SRT Monitor has the `FileStatusOutput=true` option, which writes the current stream status to a text file. AdiIRC can read that, and, for example, execute a command when a certain condition is met.

If this example, the word "**DOWN**" is part of the text written to the text file whenever a stream goes down. Using AdiIRC scripting, you can have a script search for the word "**DOWN**", and say, execute a file when it's found.

Within [**outputSRT.ini**](https://github.com/loopy750/SRT-Stats-Monitor/blob/main/modifications/adiirc/outputSRT.ini), just before the **//msg** line, you would add something like

`  if (DOWN isin $read(%statusFile)) /run cmd.exe`

Now, whenever your stream fails, SRT Monitor will write to the text file something like "**[STREAM DOWN]**", AdiIRC will see this, and execute cmd.exe, and you will see the Windows cmd window pop up.

**Comment by modemmike** [comment]
That's a great solution.

What I was suggesting is calling CURL to whatever URL specified in the INI with the payload of the status but knowing (now) that the status could be in a text file is all I need.

Thank you for your time! Much appreciated.
