### ISSUE TITLE
NGINX RTMP doesn't print bitrate by itself

### ISSUE THREAD

**Issue by RadegasTCZ** [loopy750/SRT-Stats-Monitor#32]
I have SRT on SLS and RTMP on NGINX ingests set up and it seems not to be printing the output bitrate to the standalone file from the NGINX, but it prints to the overall status file. Images to follow.

Both inputs at the same time do properly print bitrates
![image](https://github.com/user-attachments/assets/6d00697e-adb8-42d1-b5ea-b22091b6ad0b)

Input 1 (SLS) does print as well.
![image](https://github.com/user-attachments/assets/180af37d-b79f-48be-9f9d-3c6362cdd1db)

But there is 0 all the time on Input 2 (NGINX)
![image](https://github.com/user-attachments/assets/c3f010ca-8a2b-402c-bfef-08693712afcc)

**Comment by loopy750** [comment]
It looks like RTMP streams weren't considered for outputting to those files when support was added, that's why only SLS was working. Should be fixed now. And also seems like a good time to release v1.1.3.

Download from here.

https://github.com/loopy750/SRT-Stats-Monitor/releases

**Comment by RadegasTCZ** [comment]
Yes it does work now, thanks for the update!
![image](https://github.com/user-attachments/assets/92bb1357-52c0-44fe-8e75-ed89017d091b)
