### ISSUE TITLE
Problem with LBR scene and iphone 

### ISSUE THREAD

**Issue by djr0x** [loopy750/SRT-Stats-Monitor#4]
hi, thank you for the program, it works fine but has a problem, with recent iPhones using cinematic or auto stabilization, if you change camera from front to rear it creates 1 second of lag larix, the program interprets it as lbr scene and then goes always in LBR scene change when you change front / rear camera, can fix it? Thank you

**Comment by loopy750** [comment]
This is a very good suggestion for LBR in general, and something I'll be adding. I don't own an iPhone so you'll have to report back.

Please try the attached file and see how it goes, it can be run from any folder (portable/beta version). And add the following line to config.ini -

```
SceneLBRDelay=1
```

0 is the default setting with no delay, hence LBR will the triggered the moment low bitrate is detected. 1 equals one second of low bitrate required before the trigger. 2 equals two seconds required, etc.

Please let me know if you're running either 1 or 2 stream configuration, and the results of each of those values, 0, 1, & 2.

[loopy_srt_monitor.zip](https://github.com/loopy750/SRT-Stats-Monitor/files/7453121/loopy_srt_monitor.zip)

**Comment by djr0x** [comment]
> This is a very good suggestion for LBR in general, and something I'll be adding. I don't own an iPhone so you'll have to report back.
> 
> Please try the attached file and see how it goes, it can be run from any folder (portable/beta version). And add the following line to config.ini -
> 
> ```
> SceneLBRDelay=1
> ```
> 
> 0 is the default setting with no delay, hence LBR will the triggered the moment low bitrate is detected. 1 equals one second of low bitrate required before the trigger. 2 equals two seconds required, etc.
> 
> Please let me know if you're running either 1 or 2 stream configuration, and the results of each of those values, 0, 1, & 2.
> 
> [loopy_srt_monitor.zip](https://github.com/loopy750/SRT-Stats-Monitor/files/7453121/loopy_srt_monitor.zip)

hi , thank you , 2 seconds is perfect ,   using  1 cam

**Comment by AlfaTelevision** [comment]
Hi, 
I also tried and and the 2 seconds are perfect
I have a question, what is the intro scene for? And how can I use it?

**Comment by loopy750** [comment]
>  I have a question, what is the intro scene for? And how can I use it?

It is a one-off scene selected on program launch if no streams are running. The scene can be whatever you want.
