### ISSUE TITLE
Multiple Scene Bypass

### ISSUE THREAD

**Issue by shaddowgigs** [loopy750/SRT-Stats-Monitor#6]
Hello there, I know you have the option to assign a scene that will bypass the auto switching by assigning it here "SceneBypass=" and that works great, but my setup now have multiple scenes that I don't want it to change automatically like my Intro, Outro, Private, etc.. Is there a way to assign multiple scenes to be bypassed?

**Comment by loopy750** [comment]
Hi, if I read correctly, what you're after is

```
SceneBypass=scene name 1
SceneBypass2=scene name 2

...

SceneBypass8=scene name 8
SceneBypass9=scene name 9
```

This was a simple update, and it now available in the beta, at

https://github.com/loopy750/SRT-Stats-Monitor/tree/beta

Uncheck "Download obs-websocket-js" when installing to avoid the beta version of obs-websocket-js being installed.

**Comment by loopy750** [comment]
Hi, if I read correctly, what you're after is

```
SceneBypass=scene name 1
SceneBypass2=scene name 2

...

SceneBypass8=scene name 8
SceneBypass9=scene name 9
```

This was a simple update, and is now available in the beta, at

https://github.com/loopy750/SRT-Stats-Monitor/tree/beta

Uncheck "Download obs-websocket-js" when installing to avoid the beta version of obs-websocket-js being installed.

**Comment by shaddowgigs** [comment]
ufff that was fast 👍 I'll test it out today and see how it goes, thanks for making such a great tool. I could help with any testing you might need, also I would like to support your project more. Do you have a donation link?

**Comment by loopy750** [comment]
No problem, thanks for your interest.

I did setup a general donation link a while ago but never really made use of it. I'll have to look into it again. For now I have setup a donate url here but it currently contains only crypto addresses, which I am aware is not as useful or practical for most people at this point in time, but I'm cool with that either way. Thanks again anyway for your willingness to support.
