### ISSUE TITLE
Low Bitrate Szene Time

### ISSUE THREAD

**Issue by renekreher** [loopy750/SRT-Stats-Monitor#7]
Hello. thanks for the tool. I have the Problem that the switcher switches to fast the szene. Its possible to change the time wich switcher is waiting till he switch in Low Bitrate Szene?

**Comment by loopy750** [comment]
HI. I believe you are referring to #4 - you can download the file there, or you can download the latest beta at https://github.com/loopy750/SRT-Stats-Monitor/tree/beta

In config the line to add is
```
SceneLBRDelay=1
```
where "1" is the number of seconds to delay switching to Low Bitrate scene.
