### ISSUE TITLE
OBS is open? error blue screen test 6 of 10 failed :(

### ISSUE THREAD

**Issue by soyelmikelol** [loopy750/SRT-Stats-Monitor#8]
Is obs open?
test 6 of 10 failed is the error message
Blue screen with error mentioning this open obs?
and the first program I open is the obs before the srt monitor but it doesn't seem to detect it. any help on what problem may be occurring between these 2 programs so that it does not detect that the obs is running?
PS: Have I already configured the configuration file of the loopy750 SRT-Stats-Monitor and checked that both programs are allowed in the windows firewall?

**Comment by loopy750** [comment]
The **obs-websocket-js** dev had marked a beta release as the latest, and what has likely happened is what was downloaded was **obs-websocket-js** for OBS WebSockets 5.0.0, which is yet to be released. It has since been reverted, so please run ```install.cmd``` located in the ```\Documents\Loopy SRT Monitor``` folder and it should download the version required for OBS WebSockets 4.9.1.

**Comment by soyelmikelol** [comment]
Hello, thanks for the answer 😀 the version of the websocket that I downloaded was version 4.9.1.  which works with obs version 25.0.0 and above and my obs version is 27.2.4.  also install from the file install.cmd located in the \Documents\Loopy SRT Monitor folder the websocket 4.9.1 as you said and the blue screen error with the message test 6 of 10 failed keeps showing both programs not connecting for function and receive data from the SRT connection between them.  The nodejs program is necessary for the other programs to work, both obs and websocket. I tried installing both versions 16.15.1 LTS and 18.4.0, but it still does not detect that obs is running.  I don't know what can fix this obs running detection problem 😢 any other possible solution would be very appreciated✌️

**Comment by loopy750** [comment]
The latest version of nodejs is fine.

OBS WebSocket 5.0.0 has just been released which means I also need to update the program. Until then please open a command prompt and enter these commands for compatibility with 4.9.1:

```
CD /D "%USERPROFILE%\Documents\Loopy SRT Monitor"
npm install --prefix .\js obs-websocket-js@4.0.3
```

When I release a new version, it will work with both 4.9.1 & 5.0.0.

**Comment by soyelmikelol** [comment]
Hello, thanks for your answer, I tried installing the version of obs 25 and it doesn't work either.
I just entered the command in cmd and it gave me this message
added 4 packages, removed 4 packages, changed 1 package, and audited 10 packages in 2s

1 package is looking for funding
   run `npm fund` for details

found 0 vulnerabilities

C:\Users\Mike\Documents\Loopy SRT Monitor>
and in obs the option to configure websocket already installed on the pc no longer appears in the tools menu :( what could have happened with the cmd command so that the obs websocket 4.9.1 no longer works?

btw the command you sent seems to be trying to install the obs-websocket-js@4.0.3 js version which has compatibility with obs 18.0.0 and up.

**Comment by loopy750** [comment]
There is no need to install older versions of OBS. OBS 27.2.4 will work fine.

obs-websocket-js 4.0.3 is required for WebSocket 4.9.1.

If you are unable to get it working please wait a short while until I have released a new version.

**Comment by soyelmikelol** [comment]
Hi, oh perfect I did not know that you had to have this version of obs-websocket-js 4.0.3 installed
thanks for your answer. I'm about to install obs-websocket-js 4.0.3, but it doesn't bring any executable.exe. Please help me with the steps for its installation. :) On the page it mentions this about the installation but I really don't understand what steps to follow to do it.

Installation
npm install obs-websocket-js --save

bower install obs-websocket-js --save
Typescript definitions are included in this package, and are automatically generated to match the latest obs-websocket release.

**Comment by loopy750** [comment]
You seem to be making things more complicated, and I'm not really sure what changes you've made now. The new SRT Monitor version is released. If need be, uninstall the current version, delete the ```Documents\Loopy SRT Monitor``` folder and start again with the new version, carefully following all instructions. If OBS WebSocket is still giving you trouble, you can find several people who may be able to assist in sprEEzy's Discord server.

https://github.com/loopy750/SRT-Stats-Monitor/releases

**Comment by loopy750** [comment]
Guide on resolving test #6 of 10 failed - https://github.com/loopy750/SRT-Stats-Monitor/blob/main/modifications/resources/quick_start_guide.md
