### ISSUE TITLE
[Readme.md] OBS Tablet Remote and OBS Socks

### ISSUE THREAD

**Issue by fettegans** [loopy750/SRT-Stats-Monitor#9]
Hey there, 

i noticed that [OBS Tablet Remote Page](https://t2t2.github.io/obs-tablet-remote/) or any other available android app (i found) doesn't support the obs websocket 5.X yet.

Workaround: [4.x-compat](https://github.com/obsproject/obs-websocket/tree/4.x-compat)

Maybe you could take that into your readme so people are aware of this problem?

**Comment by loopy750** [comment]
That is true. Unfortunately it has brought a little more confusion than anticipated, but from what I've read, it's highly likely WebSocket 5.0 will be a part of OBS 28, so it's best people get acquainted with it now, imo.

I've added a section to the readme.md

If you believe I've left anything out, feel free to let me know.
